steps:
  # 建置 Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/message-services"
      - "."

  # 將 image 推到 Container Registry（或 Artifact Registry 也可改這裡）
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/message-services"

images:
  - "gcr.io/$PROJECT_ID/message-services"

options:
  logging: CLOUD_LOGGING_ONLY

